// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbjF4_1LJUF5LKepxN29D555vQ5kewy64',
    appId: '1:769176972888:web:6aec746ee294ab140aa42d',
    messagingSenderId: '769176972888',
    projectId: 'anime-rank-6d229',
    authDomain: 'anime-rank-6d229.firebaseapp.com',
    storageBucket: 'anime-rank-6d229.appspot.com',
    measurementId: 'G-T0F60E82TS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeqMVqB4Guth9uaWkIjUDL6ERvvVDtJsQ',
    appId: '1:769176972888:android:5ba931645ed4f5160aa42d',
    messagingSenderId: '769176972888',
    projectId: 'anime-rank-6d229',
    storageBucket: 'anime-rank-6d229.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoT7P7oCDwnjPBsyckg9538T941tr7_x0',
    appId: '1:769176972888:ios:3dc8f7462344a3700aa42d',
    messagingSenderId: '769176972888',
    projectId: 'anime-rank-6d229',
    storageBucket: 'anime-rank-6d229.appspot.com',
    iosClientId:
        '769176972888-1no3oin1pjd9ic0ls6eoc0lvsl87hipe.apps.googleusercontent.com',
    iosBundleId: 'br.com.gcapps.animerank.animeRank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoT7P7oCDwnjPBsyckg9538T941tr7_x0',
    appId: '1:769176972888:ios:3dc8f7462344a3700aa42d',
    messagingSenderId: '769176972888',
    projectId: 'anime-rank-6d229',
    storageBucket: 'anime-rank-6d229.appspot.com',
    iosClientId:
        '769176972888-1no3oin1pjd9ic0ls6eoc0lvsl87hipe.apps.googleusercontent.com',
    iosBundleId: 'br.com.gcapps.animerank.animeRank',
  );
}
